#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE auth_db;
  CREATE DATABASE users_db;
  CREATE DATABASE roles_db;
  GRANT ALL PRIVILEGES ON DATABASE auth_db TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE users_db TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE roles_db TO $POSTGRES_USER;
EOSQL
